// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package keygen

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/yournamespace/keygen/sdk/go/keygen/internal"
)

type Provider struct {
	pulumi.ProviderResourceState

	// HSM Library Location e.g. /usr/lib/softhsm/libsofthsm2.so
	HsmLocation pulumi.StringOutput `pulumi:"hsmLocation"`
	// PIN for authentication to the PKCS#11 token
	HsmPin pulumi.StringOutput `pulumi:"hsmPin"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.HsmLocation == nil {
		return nil, errors.New("invalid value for required argument 'HsmLocation'")
	}
	if args.HsmPin == nil {
		return nil, errors.New("invalid value for required argument 'HsmPin'")
	}
	if args.HsmPin != nil {
		args.HsmPin = pulumi.ToSecret(args.HsmPin).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"hsmPin",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:keygen", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// HSM Library Location e.g. /usr/lib/softhsm/libsofthsm2.so
	HsmLocation string `pulumi:"hsmLocation"`
	// PIN for authentication to the PKCS#11 token
	HsmPin string `pulumi:"hsmPin"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// HSM Library Location e.g. /usr/lib/softhsm/libsofthsm2.so
	HsmLocation pulumi.StringInput
	// PIN for authentication to the PKCS#11 token
	HsmPin pulumi.StringInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// HSM Library Location e.g. /usr/lib/softhsm/libsofthsm2.so
func (o ProviderOutput) HsmLocation() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.HsmLocation }).(pulumi.StringOutput)
}

// PIN for authentication to the PKCS#11 token
func (o ProviderOutput) HsmPin() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.HsmPin }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
