// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pem

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/yournamespace/keygen/sdk/go/keygen/internal"
)

func Encode(ctx *pulumi.Context, args *EncodeArgs, opts ...pulumi.InvokeOption) (*EncodeResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv EncodeResult
	err := ctx.Invoke("keygen:pem:encode", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type EncodeArgs struct {
	Bytes  string            `pulumi:"bytes"`
	Header map[string]string `pulumi:"header"`
	Type   string            `pulumi:"type"`
}

type EncodeResult struct {
	Result string `pulumi:"result"`
}

func EncodeOutput(ctx *pulumi.Context, args EncodeOutputArgs, opts ...pulumi.InvokeOption) EncodeResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (EncodeResultOutput, error) {
			args := v.(EncodeArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("keygen:pem:encode", args, EncodeResultOutput{}, options).(EncodeResultOutput), nil
		}).(EncodeResultOutput)
}

type EncodeOutputArgs struct {
	Bytes  pulumi.StringInput    `pulumi:"bytes"`
	Header pulumi.StringMapInput `pulumi:"header"`
	Type   pulumi.StringInput    `pulumi:"type"`
}

func (EncodeOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*EncodeArgs)(nil)).Elem()
}

type EncodeResultOutput struct{ *pulumi.OutputState }

func (EncodeResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*EncodeResult)(nil)).Elem()
}

func (o EncodeResultOutput) ToEncodeResultOutput() EncodeResultOutput {
	return o
}

func (o EncodeResultOutput) ToEncodeResultOutputWithContext(ctx context.Context) EncodeResultOutput {
	return o
}

func (o EncodeResultOutput) Result() pulumi.StringOutput {
	return o.ApplyT(func(v EncodeResult) string { return v.Result }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(EncodeResultOutput{})
}
