// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package age

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/yournamespace/keygen/sdk/go/keygen/internal"
)

// Decrypt decrypts a file encrypted to one or more identities.
func Decrypt(ctx *pulumi.Context, args *DecryptArgs, opts ...pulumi.InvokeOption) (*DecryptResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv DecryptResult
	err := ctx.Invoke("keygen:age:decrypt", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type DecryptArgs struct {
	// The ciphertext to decrypt.
	Ciphertext string `pulumi:"ciphertext"`
	// The identity to decrypt with.
	Identity string `pulumi:"identity"`
}

type DecryptResult struct {
	Result string `pulumi:"result"`
}

func DecryptOutput(ctx *pulumi.Context, args DecryptOutputArgs, opts ...pulumi.InvokeOption) DecryptResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (DecryptResultOutput, error) {
			args := v.(DecryptArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("keygen:age:decrypt", args, DecryptResultOutput{}, options).(DecryptResultOutput), nil
		}).(DecryptResultOutput)
}

type DecryptOutputArgs struct {
	// The ciphertext to decrypt.
	Ciphertext pulumi.StringInput `pulumi:"ciphertext"`
	// The identity to decrypt with.
	Identity pulumi.StringInput `pulumi:"identity"`
}

func (DecryptOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DecryptArgs)(nil)).Elem()
}

type DecryptResultOutput struct{ *pulumi.OutputState }

func (DecryptResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DecryptResult)(nil)).Elem()
}

func (o DecryptResultOutput) ToDecryptResultOutput() DecryptResultOutput {
	return o
}

func (o DecryptResultOutput) ToDecryptResultOutputWithContext(ctx context.Context) DecryptResultOutput {
	return o
}

func (o DecryptResultOutput) Result() pulumi.StringOutput {
	return o.ApplyT(func(v DecryptResult) string { return v.Result }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(DecryptResultOutput{})
}
