// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package age

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/yournamespace/keygen/sdk/go/keygen/internal"
)

// Encrypt encrypts a file to one or more recipients.
func Encrypt(ctx *pulumi.Context, args *EncryptArgs, opts ...pulumi.InvokeOption) (*EncryptResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv EncryptResult
	err := ctx.Invoke("keygen:age:encrypt", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type EncryptArgs struct {
	// The plaintext to encrypt.
	Plaintext string `pulumi:"plaintext"`
	// The recipients to encrypt to.
	Recipients []string `pulumi:"recipients"`
}

type EncryptResult struct {
	Result string `pulumi:"result"`
}

func EncryptOutput(ctx *pulumi.Context, args EncryptOutputArgs, opts ...pulumi.InvokeOption) EncryptResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (EncryptResultOutput, error) {
			args := v.(EncryptArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("keygen:age:encrypt", args, EncryptResultOutput{}, options).(EncryptResultOutput), nil
		}).(EncryptResultOutput)
}

type EncryptOutputArgs struct {
	// The plaintext to encrypt.
	Plaintext pulumi.StringInput `pulumi:"plaintext"`
	// The recipients to encrypt to.
	Recipients pulumi.StringArrayInput `pulumi:"recipients"`
}

func (EncryptOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*EncryptArgs)(nil)).Elem()
}

type EncryptResultOutput struct{ *pulumi.OutputState }

func (EncryptResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*EncryptResult)(nil)).Elem()
}

func (o EncryptResultOutput) ToEncryptResultOutput() EncryptResultOutput {
	return o
}

func (o EncryptResultOutput) ToEncryptResultOutputWithContext(ctx context.Context) EncryptResultOutput {
	return o
}

func (o EncryptResultOutput) Result() pulumi.StringOutput {
	return o.ApplyT(func(v EncryptResult) string { return v.Result }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(EncryptResultOutput{})
}
