// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * A symmetric data key for use outside of AWS KMS
 */
export class DataKey extends pulumi.CustomResource {
    /**
     * Get an existing DataKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): DataKey {
        return new DataKey(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'keygen:awskms:DataKey';

    /**
     * Returns true if the given object is an instance of DataKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DataKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DataKey.__pulumiType;
    }

    declare public /*out*/ readonly ciphertextBlob: pulumi.Output<string>;
    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * Number of hours, before expiration, that the key will be renewed.
     */
    declare public readonly earlyRenewalHours: pulumi.Output<number | undefined>;
    /**
     * The ID of the KMS key to use for encrypting the data key.
     */
    declare public readonly keyId: pulumi.Output<string>;
    /**
     * The type of data key to generate. AES_128 | AES_256. You must specify either the KeySpec or the NumberOfBytes parameter (but not both)
     */
    declare public readonly keySpec: pulumi.Output<string>;
    /**
     * @deprecated Minimum value of 1. Maximum value of 1024.
     */
    declare public readonly numberOfBytes: pulumi.Output<number | undefined>;
    declare public /*out*/ readonly plaintext: pulumi.Output<string>;
    /**
     * Number of hours, after initial issuing, that the key will remain valid for.
     */
    declare public readonly validityPeriodHours: pulumi.Output<number | undefined>;
    /**
     * Whether to generate the private key without plaintext. Default is false.
     */
    declare public readonly withoutPlainText: pulumi.Output<boolean | undefined>;

    /**
     * Create a DataKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DataKeyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.keyId === undefined && !opts.urn) {
                throw new Error("Missing required property 'keyId'");
            }
            if (args?.keySpec === undefined && !opts.urn) {
                throw new Error("Missing required property 'keySpec'");
            }
            resourceInputs["earlyRenewalHours"] = args?.earlyRenewalHours;
            resourceInputs["keyId"] = args?.keyId;
            resourceInputs["keySpec"] = args?.keySpec;
            resourceInputs["numberOfBytes"] = args?.numberOfBytes;
            resourceInputs["validityPeriodHours"] = args?.validityPeriodHours;
            resourceInputs["withoutPlainText"] = args?.withoutPlainText;
            resourceInputs["ciphertextBlob"] = undefined /*out*/;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["plaintext"] = undefined /*out*/;
        } else {
            resourceInputs["ciphertextBlob"] = undefined /*out*/;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["earlyRenewalHours"] = undefined /*out*/;
            resourceInputs["keyId"] = undefined /*out*/;
            resourceInputs["keySpec"] = undefined /*out*/;
            resourceInputs["numberOfBytes"] = undefined /*out*/;
            resourceInputs["plaintext"] = undefined /*out*/;
            resourceInputs["validityPeriodHours"] = undefined /*out*/;
            resourceInputs["withoutPlainText"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["plaintext"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(DataKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a DataKey resource.
 */
export interface DataKeyArgs {
    /**
     * Number of hours, before expiration, that the key will be renewed.
     */
    earlyRenewalHours?: pulumi.Input<number>;
    /**
     * The ID of the KMS key to use for encrypting the data key.
     */
    keyId: pulumi.Input<string>;
    /**
     * The type of data key to generate. AES_128 | AES_256. You must specify either the KeySpec or the NumberOfBytes parameter (but not both)
     */
    keySpec: pulumi.Input<string>;
    /**
     * @deprecated Minimum value of 1. Maximum value of 1024.
     */
    numberOfBytes?: pulumi.Input<number>;
    /**
     * Number of hours, after initial issuing, that the key will remain valid for.
     */
    validityPeriodHours?: pulumi.Input<number>;
    /**
     * Whether to generate the private key without plaintext. Default is false.
     */
    withoutPlainText?: pulumi.Input<boolean>;
}
