// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Encrypt encrypts a file to one or more recipients.
 */
export function encrypt(args: EncryptArgs, opts?: pulumi.InvokeOptions): Promise<EncryptResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("keygen:awskms:encrypt", {
        "encryptionAlgorithm": args.encryptionAlgorithm,
        "keyId": args.keyId,
        "plaintext": args.plaintext,
    }, opts);
}

export interface EncryptArgs {
    /**
     * The encryption algorithm to use. SYMMETRIC_DEFAULT | RSAES_OAEP_SHA_1 | RSAES_OAEP_SHA_256 | SM2PKE
     */
    encryptionAlgorithm?: string;
    /**
     * Identifies the KMS key to use in the encryption operation
     */
    keyId: string;
    /**
     * The plaintext to encrypt. Base64-encoded binary data object
     */
    plaintext: string;
}

export interface EncryptResult {
    readonly result: string;
}
/**
 * Encrypt encrypts a file to one or more recipients.
 */
export function encryptOutput(args: EncryptOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<EncryptResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("keygen:awskms:encrypt", {
        "encryptionAlgorithm": args.encryptionAlgorithm,
        "keyId": args.keyId,
        "plaintext": args.plaintext,
    }, opts);
}

export interface EncryptOutputArgs {
    /**
     * The encryption algorithm to use. SYMMETRIC_DEFAULT | RSAES_OAEP_SHA_1 | RSAES_OAEP_SHA_256 | SM2PKE
     */
    encryptionAlgorithm?: pulumi.Input<string>;
    /**
     * Identifies the KMS key to use in the encryption operation
     */
    keyId: pulumi.Input<string>;
    /**
     * The plaintext to encrypt. Base64-encoded binary data object
     */
    plaintext: pulumi.Input<string>;
}
