// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { DataKeyArgs } from "./dataKey";
export type DataKey = import("./dataKey").DataKey;
export const DataKey: typeof import("./dataKey").DataKey = null as any;
utilities.lazyLoad(exports, ["DataKey"], () => require("./dataKey"));

export { DataKeyPairArgs } from "./dataKeyPair";
export type DataKeyPair = import("./dataKeyPair").DataKeyPair;
export const DataKeyPair: typeof import("./dataKeyPair").DataKeyPair = null as any;
utilities.lazyLoad(exports, ["DataKeyPair"], () => require("./dataKeyPair"));

export { DecryptArgs, DecryptResult, DecryptOutputArgs } from "./decrypt";
export const decrypt: typeof import("./decrypt").decrypt = null as any;
export const decryptOutput: typeof import("./decrypt").decryptOutput = null as any;
utilities.lazyLoad(exports, ["decrypt","decryptOutput"], () => require("./decrypt"));

export { EncryptArgs, EncryptResult, EncryptOutputArgs } from "./encrypt";
export const encrypt: typeof import("./encrypt").encrypt = null as any;
export const encryptOutput: typeof import("./encrypt").encryptOutput = null as any;
utilities.lazyLoad(exports, ["encrypt","encryptOutput"], () => require("./encrypt"));

export { RandomArgs } from "./random";
export type Random = import("./random").Random;
export const Random: typeof import("./random").Random = null as any;
utilities.lazyLoad(exports, ["Random"], () => require("./random"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "keygen:awskms:DataKey":
                return new DataKey(name, <any>undefined, { urn })
            case "keygen:awskms:DataKeyPair":
                return new DataKeyPair(name, <any>undefined, { urn })
            case "keygen:awskms:Random":
                return new Random(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("keygen", "awskms", _module)
