// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Cryptographically secure random byte string
 */
export class Random extends pulumi.CustomResource {
    /**
     * Get an existing Random resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Random {
        return new Random(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'keygen:awskms:Random';

    /**
     * Returns true if the given object is an instance of Random.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Random {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Random.__pulumiType;
    }

    /**
     * Timestamp of creation
     */
    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * Custom key store ID
     */
    declare public readonly customKeyStoreId: pulumi.Output<string | undefined>;
    /**
     * Early renewal period in hours, before expiration
     */
    declare public readonly earlyRenewalHours: pulumi.Output<number | undefined>;
    /**
     * Number of bytes to generate
     */
    declare public readonly numberOfBytes: pulumi.Output<number>;
    /**
     * Random byte string
     */
    declare public /*out*/ readonly plaintext: pulumi.Output<string>;
    /**
     * Validity period in hours, after initial creation
     */
    declare public readonly validityPeriodHours: pulumi.Output<number | undefined>;

    /**
     * Create a Random resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RandomArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.numberOfBytes === undefined && !opts.urn) {
                throw new Error("Missing required property 'numberOfBytes'");
            }
            resourceInputs["customKeyStoreId"] = args?.customKeyStoreId;
            resourceInputs["earlyRenewalHours"] = args?.earlyRenewalHours;
            resourceInputs["numberOfBytes"] = args?.numberOfBytes;
            resourceInputs["validityPeriodHours"] = args?.validityPeriodHours;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["plaintext"] = undefined /*out*/;
        } else {
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["customKeyStoreId"] = undefined /*out*/;
            resourceInputs["earlyRenewalHours"] = undefined /*out*/;
            resourceInputs["numberOfBytes"] = undefined /*out*/;
            resourceInputs["plaintext"] = undefined /*out*/;
            resourceInputs["validityPeriodHours"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["plaintext"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Random.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Random resource.
 */
export interface RandomArgs {
    /**
     * Custom key store ID
     */
    customKeyStoreId?: pulumi.Input<string>;
    /**
     * Early renewal period in hours, before expiration
     */
    earlyRenewalHours?: pulumi.Input<number>;
    /**
     * Number of bytes to generate
     */
    numberOfBytes: pulumi.Input<number>;
    /**
     * Validity period in hours, after initial creation
     */
    validityPeriodHours?: pulumi.Input<number>;
}
