// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pkcs11

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/yournamespace/keygen/sdk/go/keygen/internal"
)

// A cryptographic key stored in a PKCS#11 HSM
type Key struct {
	pulumi.CustomResourceState

	Created pulumi.IntOutput `pulumi:"created"`
	// Number of hours, before expiration, that the key will be renewed.
	EarlyRenewalHours pulumi.IntPtrOutput `pulumi:"earlyRenewalHours"`
	// Label for the key in the HSM
	KeyLabel pulumi.StringOutput `pulumi:"keyLabel"`
	// Size of the key in bits. For RSA: 2048, 3072, 4096. For EC: 256 (P-256), 384 (P-384), 521 (P-521)
	KeySize pulumi.IntPtrOutput `pulumi:"keySize"`
	// Type of key to generate: RSA or EC (default: RSA)
	KeyType   pulumi.StringPtrOutput `pulumi:"keyType"`
	PublicKey pulumi.StringOutput    `pulumi:"publicKey"`
	// Slot number to use for the PKCS#11 session
	SlotNumber pulumi.IntPtrOutput    `pulumi:"slotNumber"`
	TokenLabel pulumi.StringPtrOutput `pulumi:"tokenLabel"`
	// Number of hours, after initial issuing, that the key will remain valid for.
	ValidityPeriodHours pulumi.IntPtrOutput `pulumi:"validityPeriodHours"`
}

// NewKey registers a new resource with the given unique name, arguments, and options.
func NewKey(ctx *pulumi.Context,
	name string, args *KeyArgs, opts ...pulumi.ResourceOption) (*Key, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.KeyLabel == nil {
		return nil, errors.New("invalid value for required argument 'KeyLabel'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Key
	err := ctx.RegisterResource("keygen:pkcs11:Key", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetKey gets an existing Key resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *KeyState, opts ...pulumi.ResourceOption) (*Key, error) {
	var resource Key
	err := ctx.ReadResource("keygen:pkcs11:Key", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Key resources.
type keyState struct {
}

type KeyState struct {
}

func (KeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*keyState)(nil)).Elem()
}

type keyArgs struct {
	// Number of hours, before expiration, that the key will be renewed.
	EarlyRenewalHours *int `pulumi:"earlyRenewalHours"`
	// Label for the key in the HSM
	KeyLabel string `pulumi:"keyLabel"`
	// Size of the key in bits. For RSA: 2048, 3072, 4096. For EC: 256 (P-256), 384 (P-384), 521 (P-521)
	KeySize *int `pulumi:"keySize"`
	// Type of key to generate: RSA or EC (default: RSA)
	KeyType *string `pulumi:"keyType"`
	// Slot number to use for the PKCS#11 session
	SlotNumber *int    `pulumi:"slotNumber"`
	TokenLabel *string `pulumi:"tokenLabel"`
	// Number of hours, after initial issuing, that the key will remain valid for.
	ValidityPeriodHours *int `pulumi:"validityPeriodHours"`
}

// The set of arguments for constructing a Key resource.
type KeyArgs struct {
	// Number of hours, before expiration, that the key will be renewed.
	EarlyRenewalHours pulumi.IntPtrInput
	// Label for the key in the HSM
	KeyLabel pulumi.StringInput
	// Size of the key in bits. For RSA: 2048, 3072, 4096. For EC: 256 (P-256), 384 (P-384), 521 (P-521)
	KeySize pulumi.IntPtrInput
	// Type of key to generate: RSA or EC (default: RSA)
	KeyType pulumi.StringPtrInput
	// Slot number to use for the PKCS#11 session
	SlotNumber pulumi.IntPtrInput
	TokenLabel pulumi.StringPtrInput
	// Number of hours, after initial issuing, that the key will remain valid for.
	ValidityPeriodHours pulumi.IntPtrInput
}

func (KeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*keyArgs)(nil)).Elem()
}

type KeyInput interface {
	pulumi.Input

	ToKeyOutput() KeyOutput
	ToKeyOutputWithContext(ctx context.Context) KeyOutput
}

func (*Key) ElementType() reflect.Type {
	return reflect.TypeOf((**Key)(nil)).Elem()
}

func (i *Key) ToKeyOutput() KeyOutput {
	return i.ToKeyOutputWithContext(context.Background())
}

func (i *Key) ToKeyOutputWithContext(ctx context.Context) KeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KeyOutput)
}

// KeyArrayInput is an input type that accepts KeyArray and KeyArrayOutput values.
// You can construct a concrete instance of `KeyArrayInput` via:
//
//	KeyArray{ KeyArgs{...} }
type KeyArrayInput interface {
	pulumi.Input

	ToKeyArrayOutput() KeyArrayOutput
	ToKeyArrayOutputWithContext(context.Context) KeyArrayOutput
}

type KeyArray []KeyInput

func (KeyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Key)(nil)).Elem()
}

func (i KeyArray) ToKeyArrayOutput() KeyArrayOutput {
	return i.ToKeyArrayOutputWithContext(context.Background())
}

func (i KeyArray) ToKeyArrayOutputWithContext(ctx context.Context) KeyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KeyArrayOutput)
}

// KeyMapInput is an input type that accepts KeyMap and KeyMapOutput values.
// You can construct a concrete instance of `KeyMapInput` via:
//
//	KeyMap{ "key": KeyArgs{...} }
type KeyMapInput interface {
	pulumi.Input

	ToKeyMapOutput() KeyMapOutput
	ToKeyMapOutputWithContext(context.Context) KeyMapOutput
}

type KeyMap map[string]KeyInput

func (KeyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Key)(nil)).Elem()
}

func (i KeyMap) ToKeyMapOutput() KeyMapOutput {
	return i.ToKeyMapOutputWithContext(context.Background())
}

func (i KeyMap) ToKeyMapOutputWithContext(ctx context.Context) KeyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KeyMapOutput)
}

type KeyOutput struct{ *pulumi.OutputState }

func (KeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Key)(nil)).Elem()
}

func (o KeyOutput) ToKeyOutput() KeyOutput {
	return o
}

func (o KeyOutput) ToKeyOutputWithContext(ctx context.Context) KeyOutput {
	return o
}

func (o KeyOutput) Created() pulumi.IntOutput {
	return o.ApplyT(func(v *Key) pulumi.IntOutput { return v.Created }).(pulumi.IntOutput)
}

// Number of hours, before expiration, that the key will be renewed.
func (o KeyOutput) EarlyRenewalHours() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Key) pulumi.IntPtrOutput { return v.EarlyRenewalHours }).(pulumi.IntPtrOutput)
}

// Label for the key in the HSM
func (o KeyOutput) KeyLabel() pulumi.StringOutput {
	return o.ApplyT(func(v *Key) pulumi.StringOutput { return v.KeyLabel }).(pulumi.StringOutput)
}

// Size of the key in bits. For RSA: 2048, 3072, 4096. For EC: 256 (P-256), 384 (P-384), 521 (P-521)
func (o KeyOutput) KeySize() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Key) pulumi.IntPtrOutput { return v.KeySize }).(pulumi.IntPtrOutput)
}

// Type of key to generate: RSA or EC (default: RSA)
func (o KeyOutput) KeyType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Key) pulumi.StringPtrOutput { return v.KeyType }).(pulumi.StringPtrOutput)
}

func (o KeyOutput) PublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *Key) pulumi.StringOutput { return v.PublicKey }).(pulumi.StringOutput)
}

// Slot number to use for the PKCS#11 session
func (o KeyOutput) SlotNumber() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Key) pulumi.IntPtrOutput { return v.SlotNumber }).(pulumi.IntPtrOutput)
}

func (o KeyOutput) TokenLabel() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Key) pulumi.StringPtrOutput { return v.TokenLabel }).(pulumi.StringPtrOutput)
}

// Number of hours, after initial issuing, that the key will remain valid for.
func (o KeyOutput) ValidityPeriodHours() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Key) pulumi.IntPtrOutput { return v.ValidityPeriodHours }).(pulumi.IntPtrOutput)
}

type KeyArrayOutput struct{ *pulumi.OutputState }

func (KeyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Key)(nil)).Elem()
}

func (o KeyArrayOutput) ToKeyArrayOutput() KeyArrayOutput {
	return o
}

func (o KeyArrayOutput) ToKeyArrayOutputWithContext(ctx context.Context) KeyArrayOutput {
	return o
}

func (o KeyArrayOutput) Index(i pulumi.IntInput) KeyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Key {
		return vs[0].([]*Key)[vs[1].(int)]
	}).(KeyOutput)
}

type KeyMapOutput struct{ *pulumi.OutputState }

func (KeyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Key)(nil)).Elem()
}

func (o KeyMapOutput) ToKeyMapOutput() KeyMapOutput {
	return o
}

func (o KeyMapOutput) ToKeyMapOutputWithContext(ctx context.Context) KeyMapOutput {
	return o
}

func (o KeyMapOutput) MapIndex(k pulumi.StringInput) KeyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Key {
		return vs[0].(map[string]*Key)[vs[1].(string)]
	}).(KeyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*KeyInput)(nil)).Elem(), &Key{})
	pulumi.RegisterInputType(reflect.TypeOf((*KeyArrayInput)(nil)).Elem(), KeyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*KeyMapInput)(nil)).Elem(), KeyMap{})
	pulumi.RegisterOutputType(KeyOutput{})
	pulumi.RegisterOutputType(KeyArrayOutput{})
	pulumi.RegisterOutputType(KeyMapOutput{})
}
