// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Decrypt decrypts data using a key stored in a PKCS#11 HSM.
 */
export function decrypt(args: DecryptArgs, opts?: pulumi.InvokeOptions): Promise<DecryptResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("keygen:pkcs11:decrypt", {
        "ciphertext": args.ciphertext,
        "keyLabel": args.keyLabel,
        "slotNumber": args.slotNumber,
        "tokenLabel": args.tokenLabel,
    }, opts);
}

export interface DecryptArgs {
    /**
     * The ciphertext to decrypt (base64-encoded)
     */
    ciphertext: string;
    /**
     * Label of the key to use for decryption
     */
    keyLabel: string;
    /**
     * Slot number to use for the PKCS#11 session
     */
    slotNumber?: number;
    tokenLabel: string;
}

export interface DecryptResult {
    readonly result: string;
}
/**
 * Decrypt decrypts data using a key stored in a PKCS#11 HSM.
 */
export function decryptOutput(args: DecryptOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<DecryptResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("keygen:pkcs11:decrypt", {
        "ciphertext": args.ciphertext,
        "keyLabel": args.keyLabel,
        "slotNumber": args.slotNumber,
        "tokenLabel": args.tokenLabel,
    }, opts);
}

export interface DecryptOutputArgs {
    /**
     * The ciphertext to decrypt (base64-encoded)
     */
    ciphertext: pulumi.Input<string>;
    /**
     * Label of the key to use for decryption
     */
    keyLabel: pulumi.Input<string>;
    /**
     * Slot number to use for the PKCS#11 session
     */
    slotNumber?: pulumi.Input<number>;
    tokenLabel: pulumi.Input<string>;
}
