// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Encrypt encrypts data using a key stored in a PKCS#11 HSM.
 */
export function encrypt(args: EncryptArgs, opts?: pulumi.InvokeOptions): Promise<EncryptResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("keygen:pkcs11:encrypt", {
        "keyLabel": args.keyLabel,
        "plaintext": args.plaintext,
        "slotNumber": args.slotNumber,
        "tokenLabel": args.tokenLabel,
    }, opts);
}

export interface EncryptArgs {
    /**
     * Label of the key to use for encryption
     */
    keyLabel: string;
    /**
     * The plaintext to encrypt (base64-encoded)
     */
    plaintext: string;
    /**
     * Slot number to use for the PKCS#11 session
     */
    slotNumber?: number;
    tokenLabel?: string;
}

export interface EncryptResult {
    readonly result: string;
}
/**
 * Encrypt encrypts data using a key stored in a PKCS#11 HSM.
 */
export function encryptOutput(args: EncryptOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<EncryptResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("keygen:pkcs11:encrypt", {
        "keyLabel": args.keyLabel,
        "plaintext": args.plaintext,
        "slotNumber": args.slotNumber,
        "tokenLabel": args.tokenLabel,
    }, opts);
}

export interface EncryptOutputArgs {
    /**
     * Label of the key to use for encryption
     */
    keyLabel: pulumi.Input<string>;
    /**
     * The plaintext to encrypt (base64-encoded)
     */
    plaintext: pulumi.Input<string>;
    /**
     * Slot number to use for the PKCS#11 session
     */
    slotNumber?: pulumi.Input<number>;
    tokenLabel?: pulumi.Input<string>;
}
