// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { DecryptArgs, DecryptResult, DecryptOutputArgs } from "./decrypt";
export const decrypt: typeof import("./decrypt").decrypt = null as any;
export const decryptOutput: typeof import("./decrypt").decryptOutput = null as any;
utilities.lazyLoad(exports, ["decrypt","decryptOutput"], () => require("./decrypt"));

export { EncryptArgs, EncryptResult, EncryptOutputArgs } from "./encrypt";
export const encrypt: typeof import("./encrypt").encrypt = null as any;
export const encryptOutput: typeof import("./encrypt").encryptOutput = null as any;
utilities.lazyLoad(exports, ["encrypt","encryptOutput"], () => require("./encrypt"));

export { KeyArgs } from "./key";
export type Key = import("./key").Key;
export const Key: typeof import("./key").Key = null as any;
utilities.lazyLoad(exports, ["Key"], () => require("./key"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "keygen:pkcs11:Key":
                return new Key(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("keygen", "pkcs11", _module)
