// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * A cryptographic key stored in a PKCS#11 HSM
 */
export class Key extends pulumi.CustomResource {
    /**
     * Get an existing Key resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Key {
        return new Key(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'keygen:pkcs11:Key';

    /**
     * Returns true if the given object is an instance of Key.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Key {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Key.__pulumiType;
    }

    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * Number of hours, before expiration, that the key will be renewed.
     */
    declare public readonly earlyRenewalHours: pulumi.Output<number | undefined>;
    /**
     * Label for the key in the HSM
     */
    declare public readonly keyLabel: pulumi.Output<string>;
    /**
     * Size of the key in bits. For RSA: 2048, 3072, 4096. For EC: 256 (P-256), 384 (P-384), 521 (P-521)
     */
    declare public readonly keySize: pulumi.Output<number | undefined>;
    /**
     * Type of key to generate: RSA or EC (default: RSA)
     */
    declare public readonly keyType: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly publicKey: pulumi.Output<string>;
    /**
     * Slot number to use for the PKCS#11 session
     */
    declare public readonly slotNumber: pulumi.Output<number | undefined>;
    declare public readonly tokenLabel: pulumi.Output<string | undefined>;
    /**
     * Number of hours, after initial issuing, that the key will remain valid for.
     */
    declare public readonly validityPeriodHours: pulumi.Output<number | undefined>;

    /**
     * Create a Key resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: KeyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.keyLabel === undefined && !opts.urn) {
                throw new Error("Missing required property 'keyLabel'");
            }
            resourceInputs["earlyRenewalHours"] = args?.earlyRenewalHours;
            resourceInputs["keyLabel"] = args?.keyLabel;
            resourceInputs["keySize"] = args?.keySize;
            resourceInputs["keyType"] = args?.keyType;
            resourceInputs["slotNumber"] = args?.slotNumber;
            resourceInputs["tokenLabel"] = args?.tokenLabel;
            resourceInputs["validityPeriodHours"] = args?.validityPeriodHours;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["publicKey"] = undefined /*out*/;
        } else {
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["earlyRenewalHours"] = undefined /*out*/;
            resourceInputs["keyLabel"] = undefined /*out*/;
            resourceInputs["keySize"] = undefined /*out*/;
            resourceInputs["keyType"] = undefined /*out*/;
            resourceInputs["publicKey"] = undefined /*out*/;
            resourceInputs["slotNumber"] = undefined /*out*/;
            resourceInputs["tokenLabel"] = undefined /*out*/;
            resourceInputs["validityPeriodHours"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Key.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Key resource.
 */
export interface KeyArgs {
    /**
     * Number of hours, before expiration, that the key will be renewed.
     */
    earlyRenewalHours?: pulumi.Input<number>;
    /**
     * Label for the key in the HSM
     */
    keyLabel: pulumi.Input<string>;
    /**
     * Size of the key in bits. For RSA: 2048, 3072, 4096. For EC: 256 (P-256), 384 (P-384), 521 (P-521)
     */
    keySize?: pulumi.Input<number>;
    /**
     * Type of key to generate: RSA or EC (default: RSA)
     */
    keyType?: pulumi.Input<string>;
    /**
     * Slot number to use for the PKCS#11 session
     */
    slotNumber?: pulumi.Input<number>;
    tokenLabel?: pulumi.Input<string>;
    /**
     * Number of hours, after initial issuing, that the key will remain valid for.
     */
    validityPeriodHours?: pulumi.Input<number>;
}
