// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function encode(args: EncodeArgs, opts?: pulumi.InvokeOptions): Promise<EncodeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("keygen:pem:encode", {
        "bytes": args.bytes,
        "header": args.header,
        "type": args.type,
    }, opts);
}

export interface EncodeArgs {
    bytes: string;
    header: {[key: string]: string};
    type: string;
}

export interface EncodeResult {
    readonly result: string;
}
export function encodeOutput(args: EncodeOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<EncodeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("keygen:pem:encode", {
        "bytes": args.bytes,
        "header": args.header,
        "type": args.type,
    }, opts);
}

export interface EncodeOutputArgs {
    bytes: pulumi.Input<string>;
    header: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    type: pulumi.Input<string>;
}
