// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as utilities from "../utilities";

// Export members:
export { EncodeArgs, EncodeResult, EncodeOutputArgs } from "./encode";
export const encode: typeof import("./encode").encode = null as any;
export const encodeOutput: typeof import("./encode").encodeOutput = null as any;
utilities.lazyLoad(exports, ["encode","encodeOutput"], () => require("./encode"));

