// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/yournamespace/keygen/sdk/go/keygen/internal"
)

var _ = internal.GetEnvOrDefault

// HSM Library Location e.g. /usr/lib/softhsm/libsofthsm2.so
func GetHsmLocation(ctx *pulumi.Context) string {
	return config.Get(ctx, "keygen:hsmLocation")
}

// PIN for authentication to the PKCS#11 token
func GetHsmPin(ctx *pulumi.Context) string {
	return config.Get(ctx, "keygen:hsmPin")
}
