// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("keygen");

/**
 * HSM Library Location e.g. /usr/lib/softhsm/libsofthsm2.so
 */
export declare const hsmLocation: string | undefined;
Object.defineProperty(exports, "hsmLocation", {
    get() {
        return __config.get("hsmLocation");
    },
    enumerable: true,
});

/**
 * PIN for authentication to the PKCS#11 token
 */
export declare const hsmPin: string | undefined;
Object.defineProperty(exports, "hsmPin", {
    get() {
        return __config.get("hsmPin");
    },
    enumerable: true,
});

