// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package awskms

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/yournamespace/keygen/sdk/go/keygen/internal"
)

// A unique asymmetric data key pair for use outside of KMS
type DataKeyPair struct {
	pulumi.CustomResourceState

	Created pulumi.IntOutput `pulumi:"created"`
	// Number of hours, before expiration, that the key will be renewed.
	EarlyRenewalHours pulumi.IntPtrOutput `pulumi:"earlyRenewalHours"`
	// The ID of the KMS key to use for encrypting the data key.
	KeyId pulumi.StringOutput `pulumi:"keyId"`
	// The type of data key pair to generate.
	KeyPairSpec              pulumi.StringOutput `pulumi:"keyPairSpec"`
	PrivateKey               pulumi.StringOutput `pulumi:"privateKey"`
	PrivateKeyCiphertextBlob pulumi.StringOutput `pulumi:"privateKeyCiphertextBlob"`
	PublicKey                pulumi.StringOutput `pulumi:"publicKey"`
	// Number of hours, after initial issuing, that the key will remain valid for.
	ValidityPeriodHours pulumi.IntPtrOutput `pulumi:"validityPeriodHours"`
	// Whether to generate the private key without plaintext. Default is false.
	WithoutPlainText pulumi.BoolPtrOutput `pulumi:"withoutPlainText"`
}

// NewDataKeyPair registers a new resource with the given unique name, arguments, and options.
func NewDataKeyPair(ctx *pulumi.Context,
	name string, args *DataKeyPairArgs, opts ...pulumi.ResourceOption) (*DataKeyPair, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.KeyId == nil {
		return nil, errors.New("invalid value for required argument 'KeyId'")
	}
	if args.KeyPairSpec == nil {
		return nil, errors.New("invalid value for required argument 'KeyPairSpec'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"privateKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DataKeyPair
	err := ctx.RegisterResource("keygen:awskms:DataKeyPair", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDataKeyPair gets an existing DataKeyPair resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDataKeyPair(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DataKeyPairState, opts ...pulumi.ResourceOption) (*DataKeyPair, error) {
	var resource DataKeyPair
	err := ctx.ReadResource("keygen:awskms:DataKeyPair", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DataKeyPair resources.
type dataKeyPairState struct {
}

type DataKeyPairState struct {
}

func (DataKeyPairState) ElementType() reflect.Type {
	return reflect.TypeOf((*dataKeyPairState)(nil)).Elem()
}

type dataKeyPairArgs struct {
	// Number of hours, before expiration, that the key will be renewed.
	EarlyRenewalHours *int `pulumi:"earlyRenewalHours"`
	// The ID of the KMS key to use for encrypting the data key.
	KeyId string `pulumi:"keyId"`
	// The type of data key pair to generate.
	KeyPairSpec string `pulumi:"keyPairSpec"`
	// Number of hours, after initial issuing, that the key will remain valid for.
	ValidityPeriodHours *int `pulumi:"validityPeriodHours"`
	// Whether to generate the private key without plaintext. Default is false.
	WithoutPlainText *bool `pulumi:"withoutPlainText"`
}

// The set of arguments for constructing a DataKeyPair resource.
type DataKeyPairArgs struct {
	// Number of hours, before expiration, that the key will be renewed.
	EarlyRenewalHours pulumi.IntPtrInput
	// The ID of the KMS key to use for encrypting the data key.
	KeyId pulumi.StringInput
	// The type of data key pair to generate.
	KeyPairSpec pulumi.StringInput
	// Number of hours, after initial issuing, that the key will remain valid for.
	ValidityPeriodHours pulumi.IntPtrInput
	// Whether to generate the private key without plaintext. Default is false.
	WithoutPlainText pulumi.BoolPtrInput
}

func (DataKeyPairArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dataKeyPairArgs)(nil)).Elem()
}

type DataKeyPairInput interface {
	pulumi.Input

	ToDataKeyPairOutput() DataKeyPairOutput
	ToDataKeyPairOutputWithContext(ctx context.Context) DataKeyPairOutput
}

func (*DataKeyPair) ElementType() reflect.Type {
	return reflect.TypeOf((**DataKeyPair)(nil)).Elem()
}

func (i *DataKeyPair) ToDataKeyPairOutput() DataKeyPairOutput {
	return i.ToDataKeyPairOutputWithContext(context.Background())
}

func (i *DataKeyPair) ToDataKeyPairOutputWithContext(ctx context.Context) DataKeyPairOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataKeyPairOutput)
}

// DataKeyPairArrayInput is an input type that accepts DataKeyPairArray and DataKeyPairArrayOutput values.
// You can construct a concrete instance of `DataKeyPairArrayInput` via:
//
//	DataKeyPairArray{ DataKeyPairArgs{...} }
type DataKeyPairArrayInput interface {
	pulumi.Input

	ToDataKeyPairArrayOutput() DataKeyPairArrayOutput
	ToDataKeyPairArrayOutputWithContext(context.Context) DataKeyPairArrayOutput
}

type DataKeyPairArray []DataKeyPairInput

func (DataKeyPairArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DataKeyPair)(nil)).Elem()
}

func (i DataKeyPairArray) ToDataKeyPairArrayOutput() DataKeyPairArrayOutput {
	return i.ToDataKeyPairArrayOutputWithContext(context.Background())
}

func (i DataKeyPairArray) ToDataKeyPairArrayOutputWithContext(ctx context.Context) DataKeyPairArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataKeyPairArrayOutput)
}

// DataKeyPairMapInput is an input type that accepts DataKeyPairMap and DataKeyPairMapOutput values.
// You can construct a concrete instance of `DataKeyPairMapInput` via:
//
//	DataKeyPairMap{ "key": DataKeyPairArgs{...} }
type DataKeyPairMapInput interface {
	pulumi.Input

	ToDataKeyPairMapOutput() DataKeyPairMapOutput
	ToDataKeyPairMapOutputWithContext(context.Context) DataKeyPairMapOutput
}

type DataKeyPairMap map[string]DataKeyPairInput

func (DataKeyPairMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DataKeyPair)(nil)).Elem()
}

func (i DataKeyPairMap) ToDataKeyPairMapOutput() DataKeyPairMapOutput {
	return i.ToDataKeyPairMapOutputWithContext(context.Background())
}

func (i DataKeyPairMap) ToDataKeyPairMapOutputWithContext(ctx context.Context) DataKeyPairMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataKeyPairMapOutput)
}

type DataKeyPairOutput struct{ *pulumi.OutputState }

func (DataKeyPairOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DataKeyPair)(nil)).Elem()
}

func (o DataKeyPairOutput) ToDataKeyPairOutput() DataKeyPairOutput {
	return o
}

func (o DataKeyPairOutput) ToDataKeyPairOutputWithContext(ctx context.Context) DataKeyPairOutput {
	return o
}

func (o DataKeyPairOutput) Created() pulumi.IntOutput {
	return o.ApplyT(func(v *DataKeyPair) pulumi.IntOutput { return v.Created }).(pulumi.IntOutput)
}

// Number of hours, before expiration, that the key will be renewed.
func (o DataKeyPairOutput) EarlyRenewalHours() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DataKeyPair) pulumi.IntPtrOutput { return v.EarlyRenewalHours }).(pulumi.IntPtrOutput)
}

// The ID of the KMS key to use for encrypting the data key.
func (o DataKeyPairOutput) KeyId() pulumi.StringOutput {
	return o.ApplyT(func(v *DataKeyPair) pulumi.StringOutput { return v.KeyId }).(pulumi.StringOutput)
}

// The type of data key pair to generate.
func (o DataKeyPairOutput) KeyPairSpec() pulumi.StringOutput {
	return o.ApplyT(func(v *DataKeyPair) pulumi.StringOutput { return v.KeyPairSpec }).(pulumi.StringOutput)
}

func (o DataKeyPairOutput) PrivateKey() pulumi.StringOutput {
	return o.ApplyT(func(v *DataKeyPair) pulumi.StringOutput { return v.PrivateKey }).(pulumi.StringOutput)
}

func (o DataKeyPairOutput) PrivateKeyCiphertextBlob() pulumi.StringOutput {
	return o.ApplyT(func(v *DataKeyPair) pulumi.StringOutput { return v.PrivateKeyCiphertextBlob }).(pulumi.StringOutput)
}

func (o DataKeyPairOutput) PublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *DataKeyPair) pulumi.StringOutput { return v.PublicKey }).(pulumi.StringOutput)
}

// Number of hours, after initial issuing, that the key will remain valid for.
func (o DataKeyPairOutput) ValidityPeriodHours() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DataKeyPair) pulumi.IntPtrOutput { return v.ValidityPeriodHours }).(pulumi.IntPtrOutput)
}

// Whether to generate the private key without plaintext. Default is false.
func (o DataKeyPairOutput) WithoutPlainText() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DataKeyPair) pulumi.BoolPtrOutput { return v.WithoutPlainText }).(pulumi.BoolPtrOutput)
}

type DataKeyPairArrayOutput struct{ *pulumi.OutputState }

func (DataKeyPairArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DataKeyPair)(nil)).Elem()
}

func (o DataKeyPairArrayOutput) ToDataKeyPairArrayOutput() DataKeyPairArrayOutput {
	return o
}

func (o DataKeyPairArrayOutput) ToDataKeyPairArrayOutputWithContext(ctx context.Context) DataKeyPairArrayOutput {
	return o
}

func (o DataKeyPairArrayOutput) Index(i pulumi.IntInput) DataKeyPairOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DataKeyPair {
		return vs[0].([]*DataKeyPair)[vs[1].(int)]
	}).(DataKeyPairOutput)
}

type DataKeyPairMapOutput struct{ *pulumi.OutputState }

func (DataKeyPairMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DataKeyPair)(nil)).Elem()
}

func (o DataKeyPairMapOutput) ToDataKeyPairMapOutput() DataKeyPairMapOutput {
	return o
}

func (o DataKeyPairMapOutput) ToDataKeyPairMapOutputWithContext(ctx context.Context) DataKeyPairMapOutput {
	return o
}

func (o DataKeyPairMapOutput) MapIndex(k pulumi.StringInput) DataKeyPairOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DataKeyPair {
		return vs[0].(map[string]*DataKeyPair)[vs[1].(string)]
	}).(DataKeyPairOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DataKeyPairInput)(nil)).Elem(), &DataKeyPair{})
	pulumi.RegisterInputType(reflect.TypeOf((*DataKeyPairArrayInput)(nil)).Elem(), DataKeyPairArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DataKeyPairMapInput)(nil)).Elem(), DataKeyPairMap{})
	pulumi.RegisterOutputType(DataKeyPairOutput{})
	pulumi.RegisterOutputType(DataKeyPairArrayOutput{})
	pulumi.RegisterOutputType(DataKeyPairMapOutput{})
}
