// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package awskms

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/yournamespace/keygen/sdk/go/keygen/internal"
)

// A symmetric data key for use outside of AWS KMS
type DataKey struct {
	pulumi.CustomResourceState

	CiphertextBlob pulumi.StringOutput `pulumi:"ciphertextBlob"`
	Created        pulumi.IntOutput    `pulumi:"created"`
	// Number of hours, before expiration, that the key will be renewed.
	EarlyRenewalHours pulumi.IntPtrOutput `pulumi:"earlyRenewalHours"`
	// The ID of the KMS key to use for encrypting the data key.
	KeyId pulumi.StringOutput `pulumi:"keyId"`
	// The type of data key to generate. AES_128 | AES_256. You must specify either the KeySpec or the NumberOfBytes parameter (but not both)
	KeySpec pulumi.StringOutput `pulumi:"keySpec"`
	// Deprecated: Minimum value of 1. Maximum value of 1024.
	NumberOfBytes pulumi.IntPtrOutput `pulumi:"numberOfBytes"`
	Plaintext     pulumi.StringOutput `pulumi:"plaintext"`
	// Number of hours, after initial issuing, that the key will remain valid for.
	ValidityPeriodHours pulumi.IntPtrOutput `pulumi:"validityPeriodHours"`
	// Whether to generate the private key without plaintext. Default is false.
	WithoutPlainText pulumi.BoolPtrOutput `pulumi:"withoutPlainText"`
}

// NewDataKey registers a new resource with the given unique name, arguments, and options.
func NewDataKey(ctx *pulumi.Context,
	name string, args *DataKeyArgs, opts ...pulumi.ResourceOption) (*DataKey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.KeyId == nil {
		return nil, errors.New("invalid value for required argument 'KeyId'")
	}
	if args.KeySpec == nil {
		return nil, errors.New("invalid value for required argument 'KeySpec'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"plaintext",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DataKey
	err := ctx.RegisterResource("keygen:awskms:DataKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDataKey gets an existing DataKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDataKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DataKeyState, opts ...pulumi.ResourceOption) (*DataKey, error) {
	var resource DataKey
	err := ctx.ReadResource("keygen:awskms:DataKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DataKey resources.
type dataKeyState struct {
}

type DataKeyState struct {
}

func (DataKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*dataKeyState)(nil)).Elem()
}

type dataKeyArgs struct {
	// Number of hours, before expiration, that the key will be renewed.
	EarlyRenewalHours *int `pulumi:"earlyRenewalHours"`
	// The ID of the KMS key to use for encrypting the data key.
	KeyId string `pulumi:"keyId"`
	// The type of data key to generate. AES_128 | AES_256. You must specify either the KeySpec or the NumberOfBytes parameter (but not both)
	KeySpec string `pulumi:"keySpec"`
	// Deprecated: Minimum value of 1. Maximum value of 1024.
	NumberOfBytes *int `pulumi:"numberOfBytes"`
	// Number of hours, after initial issuing, that the key will remain valid for.
	ValidityPeriodHours *int `pulumi:"validityPeriodHours"`
	// Whether to generate the private key without plaintext. Default is false.
	WithoutPlainText *bool `pulumi:"withoutPlainText"`
}

// The set of arguments for constructing a DataKey resource.
type DataKeyArgs struct {
	// Number of hours, before expiration, that the key will be renewed.
	EarlyRenewalHours pulumi.IntPtrInput
	// The ID of the KMS key to use for encrypting the data key.
	KeyId pulumi.StringInput
	// The type of data key to generate. AES_128 | AES_256. You must specify either the KeySpec or the NumberOfBytes parameter (but not both)
	KeySpec pulumi.StringInput
	// Deprecated: Minimum value of 1. Maximum value of 1024.
	NumberOfBytes pulumi.IntPtrInput
	// Number of hours, after initial issuing, that the key will remain valid for.
	ValidityPeriodHours pulumi.IntPtrInput
	// Whether to generate the private key without plaintext. Default is false.
	WithoutPlainText pulumi.BoolPtrInput
}

func (DataKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dataKeyArgs)(nil)).Elem()
}

type DataKeyInput interface {
	pulumi.Input

	ToDataKeyOutput() DataKeyOutput
	ToDataKeyOutputWithContext(ctx context.Context) DataKeyOutput
}

func (*DataKey) ElementType() reflect.Type {
	return reflect.TypeOf((**DataKey)(nil)).Elem()
}

func (i *DataKey) ToDataKeyOutput() DataKeyOutput {
	return i.ToDataKeyOutputWithContext(context.Background())
}

func (i *DataKey) ToDataKeyOutputWithContext(ctx context.Context) DataKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataKeyOutput)
}

// DataKeyArrayInput is an input type that accepts DataKeyArray and DataKeyArrayOutput values.
// You can construct a concrete instance of `DataKeyArrayInput` via:
//
//	DataKeyArray{ DataKeyArgs{...} }
type DataKeyArrayInput interface {
	pulumi.Input

	ToDataKeyArrayOutput() DataKeyArrayOutput
	ToDataKeyArrayOutputWithContext(context.Context) DataKeyArrayOutput
}

type DataKeyArray []DataKeyInput

func (DataKeyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DataKey)(nil)).Elem()
}

func (i DataKeyArray) ToDataKeyArrayOutput() DataKeyArrayOutput {
	return i.ToDataKeyArrayOutputWithContext(context.Background())
}

func (i DataKeyArray) ToDataKeyArrayOutputWithContext(ctx context.Context) DataKeyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataKeyArrayOutput)
}

// DataKeyMapInput is an input type that accepts DataKeyMap and DataKeyMapOutput values.
// You can construct a concrete instance of `DataKeyMapInput` via:
//
//	DataKeyMap{ "key": DataKeyArgs{...} }
type DataKeyMapInput interface {
	pulumi.Input

	ToDataKeyMapOutput() DataKeyMapOutput
	ToDataKeyMapOutputWithContext(context.Context) DataKeyMapOutput
}

type DataKeyMap map[string]DataKeyInput

func (DataKeyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DataKey)(nil)).Elem()
}

func (i DataKeyMap) ToDataKeyMapOutput() DataKeyMapOutput {
	return i.ToDataKeyMapOutputWithContext(context.Background())
}

func (i DataKeyMap) ToDataKeyMapOutputWithContext(ctx context.Context) DataKeyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataKeyMapOutput)
}

type DataKeyOutput struct{ *pulumi.OutputState }

func (DataKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DataKey)(nil)).Elem()
}

func (o DataKeyOutput) ToDataKeyOutput() DataKeyOutput {
	return o
}

func (o DataKeyOutput) ToDataKeyOutputWithContext(ctx context.Context) DataKeyOutput {
	return o
}

func (o DataKeyOutput) CiphertextBlob() pulumi.StringOutput {
	return o.ApplyT(func(v *DataKey) pulumi.StringOutput { return v.CiphertextBlob }).(pulumi.StringOutput)
}

func (o DataKeyOutput) Created() pulumi.IntOutput {
	return o.ApplyT(func(v *DataKey) pulumi.IntOutput { return v.Created }).(pulumi.IntOutput)
}

// Number of hours, before expiration, that the key will be renewed.
func (o DataKeyOutput) EarlyRenewalHours() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DataKey) pulumi.IntPtrOutput { return v.EarlyRenewalHours }).(pulumi.IntPtrOutput)
}

// The ID of the KMS key to use for encrypting the data key.
func (o DataKeyOutput) KeyId() pulumi.StringOutput {
	return o.ApplyT(func(v *DataKey) pulumi.StringOutput { return v.KeyId }).(pulumi.StringOutput)
}

// The type of data key to generate. AES_128 | AES_256. You must specify either the KeySpec or the NumberOfBytes parameter (but not both)
func (o DataKeyOutput) KeySpec() pulumi.StringOutput {
	return o.ApplyT(func(v *DataKey) pulumi.StringOutput { return v.KeySpec }).(pulumi.StringOutput)
}

// Deprecated: Minimum value of 1. Maximum value of 1024.
func (o DataKeyOutput) NumberOfBytes() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DataKey) pulumi.IntPtrOutput { return v.NumberOfBytes }).(pulumi.IntPtrOutput)
}

func (o DataKeyOutput) Plaintext() pulumi.StringOutput {
	return o.ApplyT(func(v *DataKey) pulumi.StringOutput { return v.Plaintext }).(pulumi.StringOutput)
}

// Number of hours, after initial issuing, that the key will remain valid for.
func (o DataKeyOutput) ValidityPeriodHours() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DataKey) pulumi.IntPtrOutput { return v.ValidityPeriodHours }).(pulumi.IntPtrOutput)
}

// Whether to generate the private key without plaintext. Default is false.
func (o DataKeyOutput) WithoutPlainText() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DataKey) pulumi.BoolPtrOutput { return v.WithoutPlainText }).(pulumi.BoolPtrOutput)
}

type DataKeyArrayOutput struct{ *pulumi.OutputState }

func (DataKeyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DataKey)(nil)).Elem()
}

func (o DataKeyArrayOutput) ToDataKeyArrayOutput() DataKeyArrayOutput {
	return o
}

func (o DataKeyArrayOutput) ToDataKeyArrayOutputWithContext(ctx context.Context) DataKeyArrayOutput {
	return o
}

func (o DataKeyArrayOutput) Index(i pulumi.IntInput) DataKeyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DataKey {
		return vs[0].([]*DataKey)[vs[1].(int)]
	}).(DataKeyOutput)
}

type DataKeyMapOutput struct{ *pulumi.OutputState }

func (DataKeyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DataKey)(nil)).Elem()
}

func (o DataKeyMapOutput) ToDataKeyMapOutput() DataKeyMapOutput {
	return o
}

func (o DataKeyMapOutput) ToDataKeyMapOutputWithContext(ctx context.Context) DataKeyMapOutput {
	return o
}

func (o DataKeyMapOutput) MapIndex(k pulumi.StringInput) DataKeyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DataKey {
		return vs[0].(map[string]*DataKey)[vs[1].(string)]
	}).(DataKeyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DataKeyInput)(nil)).Elem(), &DataKey{})
	pulumi.RegisterInputType(reflect.TypeOf((*DataKeyArrayInput)(nil)).Elem(), DataKeyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DataKeyMapInput)(nil)).Elem(), DataKeyMap{})
	pulumi.RegisterOutputType(DataKeyOutput{})
	pulumi.RegisterOutputType(DataKeyArrayOutput{})
	pulumi.RegisterOutputType(DataKeyMapOutput{})
}
