// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Decrypt decrypts a file encrypted to one or more identities.
 */
export function decrypt(args: DecryptArgs, opts?: pulumi.InvokeOptions): Promise<DecryptResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("keygen:age:decrypt", {
        "ciphertext": args.ciphertext,
        "identity": args.identity,
    }, opts);
}

export interface DecryptArgs {
    /**
     * The ciphertext to decrypt.
     */
    ciphertext: string;
    /**
     * The identity to decrypt with.
     */
    identity: string;
}

export interface DecryptResult {
    readonly result: string;
}
/**
 * Decrypt decrypts a file encrypted to one or more identities.
 */
export function decryptOutput(args: DecryptOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<DecryptResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("keygen:age:decrypt", {
        "ciphertext": args.ciphertext,
        "identity": args.identity,
    }, opts);
}

export interface DecryptOutputArgs {
    /**
     * The ciphertext to decrypt.
     */
    ciphertext: pulumi.Input<string>;
    /**
     * The identity to decrypt with.
     */
    identity: pulumi.Input<string>;
}
