// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Encrypt encrypts a file to one or more recipients.
 */
export function encrypt(args: EncryptArgs, opts?: pulumi.InvokeOptions): Promise<EncryptResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("keygen:age:encrypt", {
        "plaintext": args.plaintext,
        "recipients": args.recipients,
    }, opts);
}

export interface EncryptArgs {
    /**
     * The plaintext to encrypt.
     */
    plaintext: string;
    /**
     * The recipients to encrypt to.
     */
    recipients: string[];
}

export interface EncryptResult {
    readonly result: string;
}
/**
 * Encrypt encrypts a file to one or more recipients.
 */
export function encryptOutput(args: EncryptOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<EncryptResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("keygen:age:encrypt", {
        "plaintext": args.plaintext,
        "recipients": args.recipients,
    }, opts);
}

export interface EncryptOutputArgs {
    /**
     * The plaintext to encrypt.
     */
    plaintext: pulumi.Input<string>;
    /**
     * The recipients to encrypt to.
     */
    recipients: pulumi.Input<pulumi.Input<string>[]>;
}
