// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Age Encryption Identity, standard age private key
 */
export class Identity extends pulumi.CustomResource {
    /**
     * Get an existing Identity resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Identity {
        return new Identity(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'keygen:age:Identity';

    /**
     * Returns true if the given object is an instance of Identity.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Identity {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Identity.__pulumiType;
    }

    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * Number of hours, before expiration, that the key will be renewed.
     */
    declare public readonly earlyRenewalHours: pulumi.Output<number | undefined>;
    declare public /*out*/ readonly key: pulumi.Output<string>;
    /**
     * Custom random bytes, it must be 32 bytes, base64 encoded, optional, if not provided go rand is used to generate the random bytes
     */
    declare public readonly random: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly recipient: pulumi.Output<string>;
    /**
     * Number of hours, after initial issuing, that the key will remain valid for.
     */
    declare public readonly validityPeriodHours: pulumi.Output<number | undefined>;

    /**
     * Create a Identity resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IdentityArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["earlyRenewalHours"] = args?.earlyRenewalHours;
            resourceInputs["random"] = args?.random ? pulumi.secret(args.random) : undefined;
            resourceInputs["validityPeriodHours"] = args?.validityPeriodHours;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["key"] = undefined /*out*/;
            resourceInputs["recipient"] = undefined /*out*/;
        } else {
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["earlyRenewalHours"] = undefined /*out*/;
            resourceInputs["key"] = undefined /*out*/;
            resourceInputs["random"] = undefined /*out*/;
            resourceInputs["recipient"] = undefined /*out*/;
            resourceInputs["validityPeriodHours"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["key", "random"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Identity.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Identity resource.
 */
export interface IdentityArgs {
    /**
     * Number of hours, before expiration, that the key will be renewed.
     */
    earlyRenewalHours?: pulumi.Input<number>;
    /**
     * Custom random bytes, it must be 32 bytes, base64 encoded, optional, if not provided go rand is used to generate the random bytes
     */
    random?: pulumi.Input<string>;
    /**
     * Number of hours, after initial issuing, that the key will remain valid for.
     */
    validityPeriodHours?: pulumi.Input<number>;
}
