// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { DecryptArgs, DecryptResult, DecryptOutputArgs } from "./decrypt";
export const decrypt: typeof import("./decrypt").decrypt = null as any;
export const decryptOutput: typeof import("./decrypt").decryptOutput = null as any;
utilities.lazyLoad(exports, ["decrypt","decryptOutput"], () => require("./decrypt"));

export { EncryptArgs, EncryptResult, EncryptOutputArgs } from "./encrypt";
export const encrypt: typeof import("./encrypt").encrypt = null as any;
export const encryptOutput: typeof import("./encrypt").encryptOutput = null as any;
utilities.lazyLoad(exports, ["encrypt","encryptOutput"], () => require("./encrypt"));

export { IdentityArgs } from "./identity";
export type Identity = import("./identity").Identity;
export const Identity: typeof import("./identity").Identity = null as any;
utilities.lazyLoad(exports, ["Identity"], () => require("./identity"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "keygen:age:Identity":
                return new Identity(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("keygen", "age", _module)
