// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'keygen';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * HSM Library Location e.g. /usr/lib/softhsm/libsofthsm2.so
     */
    declare public readonly hsmLocation: pulumi.Output<string>;
    /**
     * PIN for authentication to the PKCS#11 token
     */
    declare public readonly hsmPin: pulumi.Output<string>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            if (args?.hsmLocation === undefined && !opts.urn) {
                throw new Error("Missing required property 'hsmLocation'");
            }
            if (args?.hsmPin === undefined && !opts.urn) {
                throw new Error("Missing required property 'hsmPin'");
            }
            resourceInputs["hsmLocation"] = args?.hsmLocation;
            resourceInputs["hsmPin"] = args?.hsmPin ? pulumi.secret(args.hsmPin) : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["hsmPin"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * HSM Library Location e.g. /usr/lib/softhsm/libsofthsm2.so
     */
    hsmLocation: pulumi.Input<string>;
    /**
     * PIN for authentication to the PKCS#11 token
     */
    hsmPin: pulumi.Input<string>;
}
